---

- name: Deploy AzerothCore
  hosts: build_hosts
  become: false

  pre_tasks:
    - name: Ensure all target directories are set up on the remote server
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ temp }}"
        - "{{ sql_dir }}"
        - "{{ root }}/bin/lua_scripts"


  roles:
    - role: azerothcore-build

  # post_tasks: 
  #   - name: Start the services
  #     # become: yes
  #     # become_user: azerothcore
  #     # become_method: sudo
  #     ansible.builtin.command: "/usr/bin/sudo /bin/systemctl restart {{ item }}"
  #     loop:
  #       - "authserver.service"
  #       - "worldserver.service"
  #     tags:
  #       - services
