---

- name: Install AzerothCore from binaries
  hosts: all
  become: false

  pre_tasks:
    - name: Ensure all target directories are set up on the remote server
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ temp }}"
        - "{{ sql_dir }}"
        - "{{ root }}/bin/lua_scripts"
        - "{{ root }}/bin/etc"
        - "{{ root }}/bin/etc/modules"

    - name: Set up the databases - world, auth, characters
      ansible.builtin.import_role:
        name: azerothcore-database
        tasks_from: init

  roles:
    - role: azerothcore-binary
    - role: azerothcore-database
