---

- name: Refresh the AzerothCore databases
  hosts: all
  become: false
  vars_prompt:
    - name: confirm_refresh_auth
      prompt: "Are you ABSOLUETLY sure you want to DELETE/REFRESH the AUTH DB?"
      private: false

    - name: confirm_refresh_world
      prompt: "Are you ABSOLUETLY sure you want to DELETE/REFRESH the WORLD DB?"
      private: false

    - name: confirm_refresh_characters
      prompt: "Are you ABSOLUETLY sure you want to DELETE/REFRESH the CHARACTERS DB?"
      private: false

  tasks:
    - name: Do a complete DB refresh for the AUTH DB
      when: confirm_refresh_auth | bool
      block:
        - name: Find all of the db_auth core SQL files
          ansible.builtin.find:
            paths:
              - "{{ home }}/{{ azerothcore_folder }}/source/data/sql/base/db_auth/"
            patterns:
              - "*.sql"
            file_type: file
          register: db_auth_sql_files

        - name: Find and run the base AzerothCore SQL files - db_auth
          ansible.builtin.shell: "mysql -u {{ azerothcore_db_user }} --password={{ azerothcore_db_password }} acore_auth < {{ item.path }}"
          with_items: "{{ db_auth_sql_files.files }}"

    - name: Do a complete DB refresh for the WORLD DB
      when: confirm_refresh_world | bool
      block:
        - name: Find all of the db_world core SQL files
          ansible.builtin.find:
            paths:
              - "{{ home }}/{{ azerothcore_folder }}/source/data/sql/base/db_world/"
            patterns:
              - "*.sql"
          register: db_world_sql_files

        - name: Find and run the base AzerothCore SQL files - db_world
          ansible.builtin.shell: "mysql -u {{ azerothcore_db_user }} --password={{ azerothcore_db_password }} acore_world < {{ item.path }}"
          with_items: "{{ db_world_sql_files.files }}"

    - name: Do a complete DB refresh for the CHARACTERS DB
      when: confirm_refresh_characters | bool
      block:
        - name: Find all of the db_characters core SQL files
          ansible.builtin.find:
            paths:
              - "{{ home }}/{{ azerothcore_folder }}/source/data/sql/base/db_characters/"
            patterns:
              - "*.sql"
          register: db_characters_sql_files

        - name: Find and run the base AzerothCore SQL files - db_characters
          ansible.builtin.shell: "mysql -u {{ azerothcore_db_user }} --password={{ azerothcore_db_password }} acore_characters < {{ item.path }}"
          with_items: "{{ db_characters_sql_files.files }}"
