---

- name: Upload our temp SQL file
  ansible.builtin.template:
    src: sql/dba.sql
    dest: /tmp/dba.sql
    mode: "0644"

- name: Run a raw mysql command
  ansible.builtin.shell: "mysql -u root < /tmp/dba.sql"
  args:
    creates: /var/lib/mysql/some_database_table

- name: Now delete the SQL file as we don't need it laying around
  ansible.builtin.file:
    path: /tmp/dba.sql
    state: absent
