---
- name: Create the required directory for our binaries and configs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_server_release }}/bin"
    - "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_server_release }}/bin/etc/modules"
  become: true
  tags:
    - binary

- name: Check if the worldserver has been downloaded
  ansible.builtin.stat:
    path: "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_server_release }}/bin/worldserver"
  register: worldserver_binary
  tags:
    - binary

- name: Check if the authserver has been downloaded
  ansible.builtin.stat:
    path: "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_server_release }}/bin/authserver"
  register: authserver_binary
  tags:
    - binary

- name: Copy the binaries
  ansible.builtin.copy:
    src: "{{ azerothcore_binary.path }}"
    dest: "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_server_release }}/bin/"
    mode: "0770"
  when:
    - azerothcore_binary.path is defined
  loop:
    - "worldserver"
    - "authserver"
  tags:
    - binary
