---
- name: Fetch and download our desired modules
  delegate_to: "{{ azerothcore_build_server }}"
  ansible.builtin.git:
    repo: "{{ item.git }}"
    dest: "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_source_dest_dir }}/modules/{{ item.name }}"
    version: "{{ item.version }}"
    force: true
    remote: "origin"
  loop: "{{ azerothcore_modules }}"
  tags:
    - modules

- name: Look for LUA scripts to copy
  delegate_to: "{{ azerothcore_build_server }}"
  ansible.builtin.find:
    paths:
      - "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_source_dest_dir }}/modules/"
    patterns:
      - "*.lua"
    recurse: true
    depth: 3
  register: lua_scripts
  tags:
    - modules

- name: Copy them across to our final destination
  delegate_to: "{{ azerothcore_build_server }}"
  ansible.builtin.copy:
    remote_src: true
    src: "{{ item.path }}"
    dest: "{{ root }}/bin/lua_scripts"
  loop: "{{ lua_scripts.files }}"
  when: lua_scripts.matched > 0
  tags:
    - modules
