---
#####################
# Folder creation
#####################

- name: Create server log folder
  ansible.builtin.file:
    path: "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_server_release }}/log"
    mode: "0755"
    state: "directory"
  tags:
    - configuration

# - name: Create config directories
#  file:
#    path: "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_server_release }}/bin/etc/modules"
#    state: directory
#  tags:
#    - configuration

- name: Parse and upload the configuration files
  ansible.builtin.template:
    src: "acore/etc/{{ item }}.conf"
    dest: "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_server_release }}/bin/etc/{{ item }}.conf"
    mode: "0644"
  loop:
    - worldserver
    - authserver
    - dbimport
  tags:
    - configuration

- name: Parse and upload MODULE configuration files
  ansible.builtin.template:
    src: "acore/etc/modules/{{ item }}"
    dest: "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_server_release }}/bin/etc/modules/{{ item }}"
    mode: "0644"
  loop:
    - "playerbots.conf.dist"
    - "challenge_modes.conf.dist"
    - "mod_eluna.conf.dist"
  tags:
    - configuration
