---

- name: Find all of the db_auth core SQL files
  ansible.builtin.find:
    paths:
      - "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_source_dest_dir }}/data/sql/base/db_auth/"
    patterns:
      - "*.sql"
    file_type: file
  register: db_auth_sql_files
  tags:
    - database-core
    - database-auth

- name: Find all of the db_world core SQL files
  ansible.builtin.find:
    paths:
      - "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_source_dest_dir }}/data/sql/base/db_world/"
    patterns:
      - "*.sql"
  register: db_world_sql_files
  tags:
    - database-core
    - database-world

- name: Find all of the db_characters core SQL files
  ansible.builtin.find:
    paths:
      - "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_source_dest_dir }}/data/sql/base/db_characters/"
    patterns:
      - "*.sql"
  register: db_characters_sql_files
  tags:
    - database-core
    - database-characters

# Core database tables for everything
- name: Find and run the base AzerothCore SQL files - db_auth
  ansible.builtin.shell: "mysql -u {{ azerothcore_db_user }} --password={{ azerothcore_db_password }} acore_auth < {{ item.path }}"
  register: db_auth
  changed_when: db_auth.rc != 0
  with_items: "{{ db_auth_sql_files.files }}"
  tags:
    - database-core
    - database-auth

- name: Find and run the base AzerothCore SQL files - db_world
  ansible.builtin.shell: "mysql -u {{ azerothcore_db_user }} --password={{ azerothcore_db_password }} acore_world < {{ item.path }}"
  register: db_world
  changed_when: db_world.rc != 0
  with_items: "{{ db_world_sql_files.files }}"
  tags:
    - database-core
    - database-world

- name: Find and run the base AzerothCore SQL files - db_characters
  ansible.builtin.shell: "mysql -u {{ azerothcore_db_user }} --password={{ azerothcore_db_password }} acore_characters < {{ item.path }}"
  register: db_chars
  changed_when: db_chars.rc != 0
  with_items: "{{ db_characters_sql_files.files }}"
  tags:
    - database-core
    - database-characters
